# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ This file is only read once per server start. Restart server when changed! ║
# ╚════════════════════════════════════════════════════════════════════════════╝

# Site settings
# ─────────────
baseurl: /1718-nmd2-code-irent # the subpath of your site, e.g. /blog
# host   : 127.0.0.1
# port   : 4000

# Custom Site variables
# ─────────────────────
show-style-guide: true # Show style guide in footer.
title: iRent

# Build settings
# ──────────────
defaults:
  -
    scope:
      path: "style-guide"
    values:
      layout: style-guide

exclude:
  - Gemfile
  - README.md

plugins:
# - jekyll-feed
# - jekyll-gist
# - jekyll-mentions
# - jekyll-paginate
# - jekyll-redirect-from
# - jekyll-seo-tag
# - jekyll-sitemap
  - jemoji

sass:
  style: nested
#  style: expanded
#  style: compact
#  style: compressed